## Written by Abigail Clyde. Last updated 8.18.25

## This is an R script for making the Muller plots in Figure 2 a-d. Logo plots were made with using LANL HIV sequence database tool Analyze Align (https://www.hiv.lanl.gov/content/sequence/ANALYZEALIGN/analyze_align.html)
## Input for this script is haplotype .csv generated by ER. 
## Columns for .csv were timept | haplotype (mutation) | color | number of seqs with mutation | frequency of mutation | participant | pattern |

library(dplyr)
library(ggplot2)
library(svglite)

data_path = '~/all_participant_haps.csv'
out_path = '~/Muller_Plots_121224/'
my_hap_data = read.csv(data_path)
par_list = unique(my_hap_data$participant)
my_hap_data$time_label = factor(my_hap_data$time_label, levels = c('D0', "W1", 'W4', 'W8', 'W12', 'W16'))
font <- "Arial"
my_hap_data

for (curr_par in par_list){
  curr_data = my_hap_data  %>% filter(participant == curr_par)
  curr_data$haplotype = as.factor(curr_data$haplotype)
  
  #Try and check that the frequencies all sum to 1
  hap_combos = unique(curr_data[,c('color', 'haplotype')])
  color_dict = hap_combos$color
  names(color_dict) = hap_combos$haplotype
  color_dict
  scales <- c(sort(unique(curr_data$time_label_int), decreasing = FALSE))
  scales
  ##dont think the pattern code working
  patterns = unique(curr_data[, c('pattern', 'haplotype')])
  pattern_dict = patterns$pattern
  names(pattern_dict) = patterns$haplotype
  pattern_dict
  labels <- c(sort(unique(curr_data$time_label), decreasing = FALSE))
  labels <- gsub("D", "", labels)
  labels <- gsub("W", "", labels)
  labels
  #Now plot the frequencies of haplotypes
  #I did all of the theming here to make the plots look as close to the matplotlib ones as possible
  g = ggplot(curr_data, aes(x = time_label_int, y = freq, fill = haplotype, pattern_fill=pattern)) +
    geom_area(linewidth =1) + 
    # geom_col_pattern(aes(pattern_fill = patterns), pattern='stripe') +
    #coord_fixed(ratio = 1/2) +
    #labs(title = curr_par) + 
    ylab('Mutational frequency') + 
    scale_x_continuous(name = "Time (weeks)", breaks = scales, labels = labels) +
    #guides(fill = guide_legend(reverse=TRUE)) +
    scale_fill_manual(name = hap_combos$haplotype, values = color_dict) +
    theme_classic() +
    theme(
      text = element_text(size=6, color="black", family=font), 
      legend.position="none", 
      axis.line = element_blank(), 
      axis.text = element_text(size=6, color="black", family=font), 
      panel.border=element_rect(color="black", linewidth=0.5, fill=NA))
  plot(g)
  
  ggsave(paste0(out_path, curr_par, 'haplotype backgrounds.svg'), width = 6, height = 4.5, unit="cm",dpi = 600)
}
